### PR TITLE
DD-2551 - SBS support for treediff

### PR DESCRIPTION
**Pull request by NikhilVerma**
- Implemented SBS mode for treediff
- Unified styles for SBS mode and unified mode
- Tree diff is now a toggle

**Note:** This is based on top of https://github.com/uyga/gitphp/pull/17 and https://github.com/uyga/gitphp/pull/22 . I have tested it a fair amount but with changes so big there is a chance I might have introduced a bug, we can have a round of thorough testing for this.

image

### CODE REVIEW

**Comment by hu11down** [comment]
Hi @NikhilVerma. Thanks for the pull request.
I found the following bugs:
1) Can't add new comments in sbs for added files, doesn't matter is it treediff or not.
2) Comment added in unified diff is displayed on +1 line in SBS. I suppose it's after #22.
3) Bug I wrote in #17 is still exists: when loaded, sbs panels are empty unless user scrolls on top of it.

**Comment by NikhilVerma** [comment]
@uyga Points 1 and 2 are fixed. However I still can't reproduce the bug 3. I'll try to watch the video you had shown earlier again and try to simulate the same conditions.

Do you mind telling me your Chrome version?

**Comment by hu11down** [comment]
@NikhilVerma yup, Chrome is Version 63.0.3239.108 (Official Build) (64-bit).
Now the decoration of sbs changes between two panels is broken for any mode.
screenshot 2017-12-26_17-01-40

**Comment by NikhilVerma** [comment]
@uyga  Let's do it this way. I was trying to do too many things at once :) I've removed all the code related to DD-2552 (this was the main cause of a lot of issues). The sbs diff is mostly just UI tweaks and treediff enabled. Do you mind having a look again? I hope everything is ok this time.

To improve the performance of SBS mode we need to either modify how mergely works or use some other solution entirely and it should be done separately.

**Comment by hu11down** [comment]
When treediff is off, the decoration between panels isn't working. Also panels are not expanded to page height. 
screenshot 2017-12-27_10-38-12

**Comment by NikhilVerma** [comment]
@uyga  Fixed! thanks for your patience :)

**Comment by hu11down** [comment]
Looks like it's working :)
Thank you, @NikhilVerma

**Pull request merged**
